# Session 4

## Arrays

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
1 2 4


### Numpy functions 

In [5]:
# Create an array of all zeros
# Prints "[[ 0.  0.]
#          [ 0.  0.]]"

In [6]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [7]:
# Create an array of all ones
# Prints "[[ 1.  1.]]"

In [8]:
print(np.ones(2))

[1. 1.]


In [9]:
print(np.ones((1,2)))

[[1. 1.]]


In [10]:
# Create a constant array
# Prints "[[ 7.  7.]
#          [ 7.  7.]]"

In [11]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [12]:
np.ones((2,2)) * 7

array([[7., 7.],
       [7., 7.]])

In [13]:
# Create a 2x2 identity matrix
# Prints "[[ 1.  0.]
#          [ 0.  1.]]"

In [14]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [15]:
# Create an array filled with random values
# Might print "[[ 0.91940167  0.08143941]
#               [ 0.68744134  0.87236687]]"

In [16]:
np.random.random_sample((2,2))

array([[0.80618021, 0.14623734],
       [0.0353157 , 0.03398449]])

In [17]:
50 * np.random.random_sample((2,2)) + 50

array([[83.85507271, 79.914004  ],
       [84.81469819, 87.88869245]])

### Array indexing

### Slicing

In [18]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

In [19]:
x = np.array(range(1, 13)).reshape((3,4))

In [20]:
c = np.linspace(1,12, num=12).reshape((3,4))
print(c)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [21]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]

In [22]:
d = c[0:2, 1:3]
print(d)

[[2. 3.]
 [6. 7.]]


In [23]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
# Prints "2"
# b[0, 0] is the same piece of data as a[0, 1]
# Prints "77"

In [24]:
d[0,0] = 22
print(d)

[[22.  3.]
 [ 6.  7.]]


In [25]:
print(c)

[[ 1. 22.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [26]:
dd = c.copy()[0:2, 1:3]
dd[0,0] = 222
print(c)

[[ 1. 22.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [27]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

In [29]:
x = np.array(range(1, 13)).reshape((3,4))
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
# Rank 1 view of the second row of a
# Rank 2 view of the second row of a
# Prints "[5 6 7 8] (4,)"
# Prints "[[5 6 7 8]] (1, 4)"

In [57]:
x[int(len(x)/2) : int(len(x)/2) + 1 ,:].shape

(1, 4)

In [58]:
x[int(len(x)/2) ,:].shape

(4,)

In [53]:
rank1 = x[1]
rank2 = x[1:2,:]
print(rank1.shape)
print(rank2.shape)

(4,)
(1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
# Prints "[ 2  6 10] (3,)"
# Prints "[[ 2]
#          [ 6]
#          [10]] (3, 1)"

In [70]:
x[:,1:2]

array([[ 2],
       [ 6],
       [10]])

In [65]:
x[:,1:2].shape

(3, 1)

In [68]:
x[:,1]

(3,)

In [69]:
x[:,1].shape

(3,)

### Boolean array indexing

In [73]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Find the elements of a that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where each slot of bool_idx tells
# whether that element of a is > 2.
# Prints "[[False False]
#          [ True  True]
#          [ True  True]]"

In [76]:
a > 2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
# Prints "[3 4 5 6]"

In [88]:
l = list()
for i in a:
    for j in i:
        if j > 2: l.append(j)

print(l)

[3, 4, 5, 6]


In [ ]:
# We can do all of the above in a single concise statement:
# Prints "[3 4 5 6]"

In [89]:
a[a > 2]

array([3, 4, 5, 6])

### Datatypes

In [ ]:
# Let numpy choose the datatype
# Prints "int64"

In [106]:
a.dtype

dtype('int64')

In [ ]:
# Let numpy choose the datatype
# Prints "float64"

In [116]:
np.full(1, 1.).dtype

dtype('float64')

In [ ]:
# Force a particular datatype
# Prints "int64"

In [108]:
a.astype('float32').dtype

dtype('float32')

### Array math

In [97]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [98]:
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]

In [99]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]

In [100]:
x - y

array([[-4., -4.],
       [-4., -4.]])

In [ ]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]

In [102]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]

In [103]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]

In [105]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [124]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [125]:
# Inner product of vectors; both produce 219

SyntaxError: EOL while scanning string literal (<ipython-input-129-22de81674df7>, line 1)

In [21]:
# Matrix / vector product; both produce the rank 1 array [29 67]

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]

In [ ]:
x = np.array([[1,2],[3,4]])

In [ ]:
# Compute sum of all elements; prints "10"
# Compute sum of each column; prints "[4 6]"
# Compute sum of each row; prints "[3 7]"

In [ ]:
x = np.array([[1,2], [3,4]])
# the transpose of a rank 2 array:
# Prints "[[1 2]
#          [3 4]]"
# Prints "[[1 3]
#          [2 4]]"

In [ ]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
# Prints "[1 2 3]"
# Prints "[1 2 3]"

### Broadcasting

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [ ]:
# Add v to each row of x using broadcasting
# Prints "[[ 2  2  4]
#          [ 5  5  7]
#          [ 8  8 10]
#          [11 11 13]]"